### ISSUE TITLE
"Lock Screen" menu item no longer works

### ISSUE THREAD

**Issue by tonywhelan** [collinss/Session-Manager#1] opened 2015-07-03 23:14 UTC
One of the LM or Cinnamon updates in the past year broke the "Lock Screen" function in this applet. This is because the screensaver settings were moved from org.cinnamon.screensaver to org.cinnamon.desktop.screensaver (I'm not sure of which version of LM/Cinnamon made this change).

In Linux Mint 17.x, you can fix it by editing the file
~/.local/share/cinnamon/applets/sessionManager@scollins/applet.js
Change this line:
let screensaver_settings = new Gio.Settings({ schema: "org.cinnamon.screensaver" });
to this:
let screensaver_settings = new Gio.Settings({ schema: "org.cinnamon.desktop.screensaver" });

Save the changes, log off and back on again, and all should be well.

**Comment by collinss** [comment] 2015-07-04 00:30
Thanks! That will save me some time when I get the chance to fix it. It might be a while, though, as my laptop died a couple days ago, and it might be a month or so before I can get a machine I can run the latest Cinnamon on again.

**Comment by tonywhelan** [comment] 2015-07-04 01:02
Hi Stephen

Such a nuisance when a machine dies on you. At least when you do have to 
build another, Linux is so much quicker and easier than Windows.

I had forgotten how different things were till I had to rebuild a 
friend's Win 7 machine recently. It took a whole day to install the OS 
then install audio, video, ethernet and other drivers, then do a million 
updates (MS server was not fast), then install all the software. Unlike 
Linux, Windows won't let you select a list of software then queue the 
installs, you have to be there to start each and every one, serially. My 
language deteriorated rapidly as the day wore on :(

I have also posted the fix on the applet's page on 
http://cinnamon-spices.linuxmint.com/applets/view/175 so others can see 
how to fix if they are impatient.

Tony
Canberra, AUS

**Comment by tonywhelan** [comment] 2015-07-04 01:04
PS Thank you for creating this applet. Though I can blunder my way through other people's code to try to understand it, my ability to write the code in the first place is pretty much non-existent.

**Comment by collinss** [comment] 2015-07-04 18:04
That's one of the MANY reasons I don't use Windows any more. Linux is so much easier to install and use. I'm glad you enjoy my applet. Most of the projects that I have on the spices website are ones I made because I want them, and then I share them so that hopefully others will find them as useful as I do.

**Comment by collinss** [comment] 2017-02-13 21:00
This is now fixed on the spices website. Sorry it took so long. I lost track of this issue at some point and just stumbled on it again just now.

**Comment by tonywhelan** [comment] 2017-02-13 21:45
Hi Stephen

I updated to from LM18 to LM 18.1 and the Session Manager applet shows a 
nasty red exclamation mark in the list of installed applets, and 
screen-lock doesn't work (on this machine at least). So I think 18.1 
might have moved the goalposts again :)

**Comment by collinss** [comment] 2017-02-13 23:10
Lock screen works for me here on 18.1 too. I'm not sure why it's not working for you. Could you post the contents of glass.log and .xsession-errors?

As for the red icon, it is there because I use a synchronous call on startup. This isn't really an issue because it responds so quickly, but some synchronous calls have been known to freeze Cinnamon, so we added a mechanism that scans the applet for any synchronous calls and then notifies the user if it finds any. This is to make troubleshooting easier if they experience freezes, and hopefully redirect bugs from Cinnamon to the actual culprit (we've had a number of bug reports on Cinnamon that turned out to be caused by third party applets). I plan on fixing it at some point, but I've been busy cleaning up the spices repository, so it might be a while before I get to it.

**Comment by tonywhelan** [comment] 2017-02-14 02:13
Hi Stephen, am out at present but will follow up asap.

I noticed a couple of other problems (not with this applet) on my 
upgraded machine, so I think the upgrade from 18 to 18.1 is imperfect.

**Comment by tonywhelan** [comment] 2017-02-14 06:00
Thanks Stephen

my glass.log extract:

<----------------
check_schema_and_init@/usr/share/cinnamon/js/ui/overrides.js:27
overrideGio/Gio.Settings.prototype._init@/usr/share/cinnamon/js/ui/overrides.js:74
CommandDispatcher.lock@/home/tonywhelan/.local/share/cinnamon/applets/sessionManager@scollins/applet.js:75
MenuItem.prototype.activate@/home/tonywhelan/.local/share/cinnamon/applets/sessionManager@scollins/applet.js:255
PopupBaseMenuItem.prototype._onButtonReleaseEvent@/usr/share/cinnamon/js/ui/popupMenu.js:150
---------------->

The file .xsession-errors doesn't seem to have anything obvious but 
there are a few of these:

(nemo:2054): GLib-GIO-CRITICAL **: g_app_info_equal: assertion 
'G_IS_APP_INFO (appinfo2)' failed

By the way I tried the applet on a clean build of LM18.1 on a test PC, 
and the applet's screen lock facility worked fine.

I think my heavily-customised LM18 machine didn't upgrade to 18.1 as 
perfectly as it should have. I have a couple of reasons now to do a 
clean rebuild I guess.

Tony

---

**Comment by collinss** [comment] 2017-02-23 16:00
So I looked at the line that was failing, and I can't see a reason why it would fail. The error you posted from glass.log seems to be missing the actual error message (it should be the line above what you posted). Without that I can tell _where_ it's failing, but not _why_ it's failing. If you are still getting the error, could you also post that previous line?

Also, I just pushed some changes, so it's possible that will fix your problem as well (though I wont hold my breath).

**Comment by tonywhelan** [comment] 2017-02-23 19:20
Hi Stephen

I just refreshed the applet cache and reinstalled the Session Manager 
applet. Lock Screen now works fine on my upgraded 18.1 machines as well 
as on the clean 18.1 build.

Thank you for the time you spent on this!

Tony

**Comment by collinss** [comment] 2017-02-23 19:28
Glad I could help!

**Closed as completed by collinss** 2017-02-23 19:28 UTC
